# Build pipeline for Level Flight Status web

name: "$(Date:yyyy.MM.dd)$(Rev:.r)"

trigger: none

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - task: NpmAuthenticate@0
    inputs:
      workingFile: ".npmrc"

  - script: |
      npm install
    displayName: "npm install"

  - script: |
      npm run build
    displayName: "npm build"

  - script: |
      npm run test
    displayName: "npm test"
